// Note max line length is 44 chars.

static char about[] = "\
Simulations in Physics.\n\
\n\
Source Code: https://github.com/sthaid/\n\
             proj_entropy.git\n\
\n\
THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT\n\
WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,\n\
INCLUDING BUT NOT LIMITED TO THE WARRANTIES\n\
OF MERCHANTABILITY, FITNESS FOR A \n\
PARTICULAR PURPOSE AND NONINFRINGEMENT. IN \n\
NO EVENT SHALL THE AUTHORS OR COPYRIGHT \n\
HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR\n\
OTHER LIABILITY, WHETHER IN AN ACTION OF \n\
CONTRACT, TORT OR OTHERWISE, ARISING FROM, \n\
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR\n\
THE USE OR OTHER DEALINGS IN THE SOFTWARE.\n\
";
